# Workflow to build gh pages

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install node
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      # Install the deps
      - name: Install dependencies
        run: npm install

      # Builds the project 
      - name: Build the Project
        run: | 
          npm run installemsdk
          npm run useemsdk
          chmod 755 ./build.sh
          npm run buildprod
          npm run webpacktestbuild
      
      # Create Page Artifact 
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v1
        with:
          name: github-pages
          path: test/build/
          retention-days: 1
          if-no-files-found: error

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action